refactor login to be a minimal component
Iconica-Development/flutter_login pull request #1
Opened 2022-09-27 14:49 UTC by FlutterJoey

2022-09-28 08:10 UTC, stein155 commented
Het scherm wachtwoord vergeten is niet meer opgenomen in deze branch, deze zou ook in de plug-in meegenomen worden toch?

2022-09-28 09:27 UTC, FlutterJoey commented
Yes, that is correct. I will add those tomorrow as well as fix the conflicts relating to this merge.

I will update this PR before 12 AM tomorrow.

Also, please use english 😉

2022-09-30 07:51 UTC, stein155 requested changes

2022-09-30 07:51 UTC, stein155 commented on lib/src/config/login_options.dart
> +      child: const Text('Forgot password?'),
```suggestion
      child: const Text('Reset password'),
```

2022-09-30 07:51 UTC, stein155 commented on lib/src/config/login_options.dart
> +      child: const Text('Forgot password?'),
I think this is the submit button so maybe 'Reset password' or 'Send reset email' is better here?

2022-10-03 06:25 UTC, closed without merging